server.port=${PORT:8080}
server.address=0.0.0.0
# ?? CLOUD DATABASE CONFIGURATION (NEON) ??
# Notice the 'jdbc:' at the very beginning!
spring.datasource.url=jdbc:postgresql://ep-still-firefly-aomcesrc.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner

# REPLACE 'REDACTED' WITH YOUR ACTUAL NEON PASSWORD
spring.datasource.password=${DB_PASSWORD}

# This tells Java to build the tables in the empty cloud database
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ? AI CORE CLOUD ROUTING ?
ai.service.url=${AI_CORE_URL:http://127.0.0.1:5000/analyze}
spring.main.lazy-initialization=true

spring.jpa.open-in-view=false

# Force database mapping to the background
spring.data.jpa.repositories.bootstrap-mode=deferred

# Stop Hikari from stalling startup to pre-fill the connection pool
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.initialization-fail-timeout=0